// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo60oPlYk4D8Gb7dTZSvG7dajTtWl18jk',
    appId: '1:135334199908:web:41d9c257702b94cb66d571',
    messagingSenderId: '135334199908',
    projectId: 'ditonton-project-a494b',
    authDomain: 'ditonton-project-a494b.firebaseapp.com',
    storageBucket: 'ditonton-project-a494b.appspot.com',
    measurementId: 'G-L25NWJD73C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8prE1jBkN4fuq5q4gZc82aTrnsN9rrg',
    appId: '1:135334199908:android:db9ba22632e126a966d571',
    messagingSenderId: '135334199908',
    projectId: 'ditonton-project-a494b',
    storageBucket: 'ditonton-project-a494b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4NIko-pP9wgaMLTGre0kkZi-RrWmD-w',
    appId: '1:135334199908:ios:30aca0e007a2bd8f66d571',
    messagingSenderId: '135334199908',
    projectId: 'ditonton-project-a494b',
    storageBucket: 'ditonton-project-a494b.appspot.com',
    iosClientId: '135334199908-evmqhf57li6fcurun4o4httkpuhpcavq.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
